// Authentication actions
export const MARK_SAVE_AUTH_CREDENTIALS = 'MARK_SAVE_AUTH_CREDENTIALS'
export const MARK_CLEAR_AUTH_CREDENTIALS = 'MARK_CLEAR_AUTH_CREDENTIALS'
export const MARK_SAVE_ENDPOINTS = 'MARK_SAVE_ENDPOINTS'
export const MARK_CLEAR_ENDPOINTS = 'MARK_CLEAR_ENDPOINTS'
export const MARK_SAVE_LAST_IDP = 'MARK_SAVE_LAST_IDP'

// Profile actions
export const MARK_LOAD_PROFILE_REQUEST = 'MARK_LOAD_PROFILE_REQUEST'
export const MARK_LOAD_PROFILE_SUCCESS = 'MARK_LOAD_PROFILE_SUCCESS'
export const MARK_CLEAR_PROFILE = 'MARK_CLEAR_PROFILE'

// Network actions
export const MARK_REGISTER_REQUEST = 'MARK_REGISTER_REQUEST'
export const MARK_REGISTER_SUCCESS = 'MARK_REGISTER_SUCCESS'

export const MARK_CREATE_CONTAINER_REQUEST = 'MARK_CREATE_CONTAINER_REQUEST'
export const MARK_CREATE_CONTAINER_SUCCESS = 'MARK_CREATE_CONTAINER_SUCCESS'

export const MARK_SAVE_BOOKMARK_REQUEST = 'MARK_SAVE_BOOKMARK_REQUEST'
export const MARK_SAVE_BOOKMARK_SUCCESS = 'MARK_SAVE_BOOKMARK_SUCCESS'

export const MARK_LOAD_REQUEST = 'MARK_LOAD_REQUEST'
export const MARK_LOAD_SUCCESS = 'MARK_LOAD_SUCCESS'

// Error actions
export const MARK_ALERT_SET = 'MARK_ALERT_SET'
export const MARK_ALERT_CLEAR = 'MARK_ALERT_CLEAR'

// Edit actions
export const MARK_EDIT_BOOKMARK = 'MARK_EDIT_BOOKMARK'
export const MARK_EDIT_BOOKMARK_CANCEL = 'MARK_EDIT_BOOKMARK_CANCEL'
export const MARK_CREATE_NEW_BOOKMARK = 'MARK_CREATE_NEW_BOOKMARK'

// Filtering/search actions
export const MARK_FILTER_ADD_TAG = 'MARK_FILTER_ADD_TAG'
export const MARK_FILTER_REMOVE_TAG = 'MARK_FILTER_REMOVE_TAG'
export const MARK_FILTER_TOGGLE_ARCHIVED = 'MARK_FILTER_TOGGLE_ARCHIVED'
