// Network actions
export const BOOKMARKS_REGISTER_REQUEST = 'BOOKMARKS_REGISTER_REQUEST'
export const BOOKMARKS_REGISTER_SUCCESS = 'BOOKMARKS_REGISTER_SUCCESS'

export const BOOKMARKS_SET_BOOKMARKS_URL = 'BOOKMARKS_SET_BOOKMARKS_URL'

export const BOOKMARKS_CREATE_RESOURCE_REQUEST = 'BOOKMARKS_CREATE_RESOURCE_REQUEST'
export const BOOKMARKS_CREATE_RESOURCE_SUCCESS = 'BOOKMARKS_CREATE_RESOURCE_SUCCESS'

export const BOOKMARKS_SAVE_BOOKMARK_REQUEST = 'BOOKMARKS_SAVE_BOOKMARK_REQUEST'
export const BOOKMARKS_SAVE_BOOKMARK_SUCCESS = 'BOOKMARKS_SAVE_BOOKMARK_SUCCESS'

export const BOOKMARKS_LOAD_REQUEST = 'BOOKMARKS_LOAD_REQUEST'
export const BOOKMARKS_LOAD_SUCCESS = 'BOOKMARKS_LOAD_SUCCESS'

// Error actions
export const BOOKMARKS_ERROR_SET = 'BOOKMARKS_ERROR_SET'
export const BOOKMARKS_ERROR_CLEAR = 'BOOKMARKS_ERROR_CLEAR'

// Edit actions
export const BOOKMARKS_EDIT_BOOKMARK = 'BOOKMARKS_EDIT_BOOKMARK'
export const BOOKMARKS_EDIT_BOOKMARK_CANCEL = 'BOOKMARKS_EDIT_BOOKMARK_CANCEL'
export const BOOKMARKS_CREATE_NEW_BOOKMARK = 'BOOKMARKS_CREATE_NEW_BOOKMARK'

// Filtering/search actions
export const BOOKMARKS_FILTER_ADD_TAG = 'BOOKMARKS_FILTER_ADD_TAG'
export const BOOKMARKS_FILTER_REMOVE_TAG = 'BOOKMARKS_FILTER_REMOVE_TAG'
export const BOOKMARKS_FILTER_TOGGLE_ARCHIVED = 'BOOKMARKS_FILTER_TOGGLE_ARCHIVED'

// Sharing actions
export const BOOKMARKS_LOAD_AUTHORIZATIONS_REQUEST = 'BOOKMARKS_LOAD_AUTHORIZATIONS_REQUEST'
export const BOOKMARKS_LOAD_AUTHORIZATIONS_SUCCESS = 'BOOKMARKS_LOAD_AUTHORIZATIONS_SUCCESS'

export const BOOKMARKS_CREATE_NEW_AUTHORIZATION = 'BOOKMARKS_CREATE_NEW_AUTHORIZATION'

export const BOOKMARKS_EDIT_PERMISSIONS = 'BOOKMARKS_EDIT_PERMISSIONS'
export const BOOKMARKS_CANCEL_EDIT_PERMISSIONS = 'BOOKMARKS_CANCEL_EDIT_PERMISSIONS'

export const BOOKMARKS_SAVE_PERMISSIONS_REQUEST = 'BOOKMARKS_SAVE_PERMISSIONS_REQUEST'
export const BOOKMARKS_SAVE_PERMISSIONS_SUCCESS = 'BOOKMARKS_SAVE_PERMISSIONS_SUCCESS'

// Social actions
export const BOOKMARKS_LOAD_PROFILE_REQUEST = 'BOOKMARKS_LOAD_PROFILE_REQUEST'
export const BOOKMARKS_LOAD_PROFILE_SUCCESS = 'BOOKMARKS_LOAD_PROFILE_SUCCESS'

export const BOOKMARKS_LOAD_CONTACTS_REQUEST = 'BOOKMARKS_LOAD_CONTACTS_REQUEST'
export const BOOKMARKS_LOAD_CONTACTS_SUCCESS = 'BOOKMARKS_LOAD_CONTACTS_SUCCESS'

export const BOOKMARKS_LOAD_CONTACT_IMAGE_REQUEST = 'BOOKMARKS_LOAD_CONTACT_IMAGE_REQUEST'
export const BOOKMARKS_LOAD_CONTACT_IMAGE_SUCCESS = 'BOOKMARKS_LOAD_CONTACT_IMAGE_SUCCESS'
