// Authentication actions
export const BOOKMARKS_SAVE_AUTH_CREDENTIALS = 'BOOKMARKS_SAVE_AUTH_CREDENTIALS'
export const BOOKMARKS_CLEAR_AUTH_CREDENTIALS = 'BOOKMARKS_CLEAR_AUTH_CREDENTIALS'
export const BOOKMARKS_SAVE_ENDPOINTS = 'BOOKMARKS_SAVE_ENDPOINTS'
export const BOOKMARKS_CLEAR_ENDPOINTS = 'BOOKMARKS_CLEAR_ENDPOINTS'

// Network actions
export const BOOKMARKS_REGISTER_REQUEST = 'BOOKMARKS_REGISTER_REQUEST'
export const BOOKMARKS_REGISTER_SUCCESS = 'BOOKMARKS_REGISTER_SUCCESS'

export const BOOKMARKS_SET_BOOKMARKS_URL = 'BOOKMARKS_SET_BOOKMARKS_URL'

export const BOOKMARKS_CREATE_CONTAINER_REQUEST = 'BOOKMARKS_CREATE_CONTAINER_REQUEST'
export const BOOKMARKS_CREATE_CONTAINER_SUCCESS = 'BOOKMARKS_CREATE_CONTAINER_SUCCESS'

export const BOOKMARKS_SAVE_BOOKMARK_REQUEST = 'BOOKMARKS_SAVE_BOOKMARK_REQUEST'
export const BOOKMARKS_SAVE_BOOKMARK_SUCCESS = 'BOOKMARKS_SAVE_BOOKMARK_SUCCESS'

export const BOOKMARKS_LOAD_REQUEST = 'BOOKMARKS_LOAD_REQUEST'
export const BOOKMARKS_LOAD_SUCCESS = 'BOOKMARKS_LOAD_SUCCESS'

// Error actions
export const BOOKMARKS_ALERT_SET = 'BOOKMARKS_ALERT_SET'
export const BOOKMARKS_ALERT_CLEAR = 'BOOKMARKS_ALERT_CLEAR'

// Edit actions
export const BOOKMARKS_EDIT_BOOKMARK = 'BOOKMARKS_EDIT_BOOKMARK'
export const BOOKMARKS_EDIT_BOOKMARK_CANCEL = 'BOOKMARKS_EDIT_BOOKMARK_CANCEL'
export const BOOKMARKS_CREATE_NEW_BOOKMARK = 'BOOKMARKS_CREATE_NEW_BOOKMARK'

// Filtering/search actions
export const BOOKMARKS_FILTER_ADD_TAG = 'BOOKMARKS_FILTER_ADD_TAG'
export const BOOKMARKS_FILTER_REMOVE_TAG = 'BOOKMARKS_FILTER_REMOVE_TAG'
export const BOOKMARKS_FILTER_TOGGLE_ARCHIVED = 'BOOKMARKS_FILTER_TOGGLE_ARCHIVED'
